baseURL: "https://laoaaa.github.io/hugo"
title: "UNTITLED"
theme: [PaperMod]
languageCode: 'en'

enableInlineShortcodes: true # 允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: false # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启
paginate: 10  # 每页显示的文章数
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
# relativeURLs: true
mainsections: ["posts"]

minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - # name: 
      url: archive
      weight: 5
    - name: universe
      url: search/
      weight: 10
    - # name: 
      url: tags/
      weight: 15
    - # name: about
      url: about/
      weight: 20
    - name: peace
      url: https://tools.burnman.net
      weight: 25  
    - # name: peace
      url: index.xml
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: 
  author: laoa

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录
  ShowFullTextinRSS: true # RSS 显示全文
  hideFooter: true # 隐藏页脚
  ShowLastMod: true #显示文章更新时间

  homeInfoParams:
    Title: a mind-hole expands
    Content: 

  profileMode:
    enabled: false
    title: +
    imageUrl: "+"
    imageTitle: +
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: 
        url: 
      - name: 
        url: 

  assets:
    disableHLJS: true


